In [1]:
import torch

In [36]:
a = torch.tensor([[[i]] * 7 for i in range(5)])
a

tensor([[[0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0]],

        [[1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1]],

        [[2],
         [2],
         [2],
         [2],
         [2],
         [2],
         [2]],

        [[3],
         [3],
         [3],
         [3],
         [3],
         [3],
         [3]],

        [[4],
         [4],
         [4],
         [4],
         [4],
         [4],
         [4]]])

In [39]:
b = [5, 5, 2, 2, 1]

In [40]:
m = torch.nn.utils.rnn.pack_padded_sequence(a, b, batch_first=True)
m

PackedSequence(data=tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [0],
        [1],
        [2],
        [3],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1]]), batch_sizes=tensor([5, 4, 2, 2, 2]), sorted_indices=None, unsorted_indices=None)

In [17]:
rnn = torch.nn.GRU(1,1,batch_first=True)

In [20]:
_,o1 = rnn(m.float())

In [22]:
o1.squeeze(0)

tensor([[-0.2886],
        [-0.7225],
        [-0.8947],
        [-0.9337],
        [-0.8815]], grad_fn=<SqueezeBackward1>)

In [24]:
o2,_ = rnn(a.float())
o2

tensor([[[-0.1242],
         [-0.1974],
         [-0.2423],
         [-0.2706],
         [-0.2886]],

        [[-0.4142],
         [-0.5892],
         [-0.6763],
         [-0.7225],
         [-0.7478]],

        [[-0.6385],
         [-0.8237],
         [-0.8947],
         [-0.9241],
         [-0.9367]],

        [[-0.7882],
         [-0.9337],
         [-0.9725],
         [-0.9836],
         [-0.9868]],

        [[-0.8815],
         [-0.9779],
         [-0.9940],
         [-0.9968],
         [-0.9973]]], grad_fn=<TransposeBackward1>)

In [35]:
b_ = torch.tensor([i-1 for i in b])
o3 = o2[:,b_,:]
o3

tensor([[[-0.2886],
         [-0.2706],
         [-0.2423],
         [-0.1974],
         [-0.1242]],

        [[-0.7478],
         [-0.7225],
         [-0.6763],
         [-0.5892],
         [-0.4142]],

        [[-0.9367],
         [-0.9241],
         [-0.8947],
         [-0.8237],
         [-0.6385]],

        [[-0.9868],
         [-0.9836],
         [-0.9725],
         [-0.9337],
         [-0.7882]],

        [[-0.9973],
         [-0.9968],
         [-0.9940],
         [-0.9779],
         [-0.8815]]], grad_fn=<IndexBackward>)